### ISSUE TITLE
Avoid explicit conversion of DataFrames

### ISSUE THREAD

**Issue by fuzzybear3965** [JuliaPy/Pandas.jl#15]
Pandas.jl takes responsibility for converting Python types into Julia types. This seems to cause a problem when it comes to using DataFrames. This has been referenced in at least issues #7, #12, and #14. I recommend moving towards an implementation of Pandas.jl that avoids this type conversion. Note that I had managed to solve my DataFrames issue through [these alterations to my code](https://github.com/JuliaPy/PyCall.jl/issues/376#issuecomment-293411255) (a big "thank you" to @stevengj).

I would implement a fix myself but most of the source relies heavily on metaprogramming lines which leave me scratching my head.

**Comment by malmaud** [comment]
Ya, that's a good idea. Should be a pretty small change.

**Comment by malmaud** [comment]
I believe this is fixed on master - can you try `Pkg.checkout("Pandas')` and see if your problem persists? I was never able to reproduce it, so I'm not positive if my fix will work for you.

**Comment by fuzzybear3965** [comment]
It seems that _an_ issue has been fixed. But, another one has reared its ugly head. Below I've included the test Julia script, the test CSV, and the output. The solution from PyCall.jl issue 376 still manages to fix the problem.

```julia
ENV["PYTHON"] = "C:\\Users\\JohnRinehart\\AppData\\Local\\Programs\\Python\\Python36\\python36.exe"

Pkg.build("PyCall")
using PyCall
import Pandas

df = Pandas.read_csv("test.csv")

@pyimport fbprophet
m = fbprophet.Prophet();
m[:fit](df)
```

_test.csv_
```csv
ds,y
2017-02-23,18.30
2017-02-24,10.90
2017-03-05,17.60
2017-03-06,10.80
2017-03-07,12.40
2017-03-08,10.40
2017-03-09,11.80
2017-03-10,17.00
2017-03-11,11.60
2017-03-12,19.50
2017-03-13,13.20
2017-03-14,16.30
2017-03-15,19.60
2017-03-16,12.90
2017-03-17,10.10
2017-03-18,9.59
2017-03-19,17.80
2017-03-20,11.30
2017-03-21,15.00
2017-03-22,17.40
2017-03-23,19.90
2017-03-24,9.94
2017-03-25,9.69
```

_Julia output_
```
julia> include("test.jl")
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using C:\Users\JohnRinehart\AppData\Local\Programs\Python\Python36\python36.exe (Python 3.6.1) at C:\Users\JohnRinehart\AppData\Local\Programs\Python\Python36\python36.exe, libpython = C:\Users\JohnRinehart\AppData\Local\Programs\Python\Python36\python36
INFO: C:\Users\JohnRinehart\.julia\v0.5\PyCall\deps\deps.jl has not changed
INFO: C:\Users\JohnRinehart\.julia\v0.5\PyCall\deps\PYTHON has not changed
ERROR: LoadError: PyError (:PyObject_Call) <class 'AttributeError'>
AttributeError("'dict' object has no attribute 'notnull'",)
  File "C:\Users\JohnRinehart\AppData\Local\Programs\Python\Python36\lib\site-packages\fbprophet\forecaster.py", line 483, in fit
    history = df[df['y'].notnull()].copy()

 in pyerr_check at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\exception.jl:56 [inlined]
 in pyerr_check at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\exception.jl:61 [inlined]
 in macro expansion at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\exception.jl:81 [inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:549
 in _pycall(::PyCall.PyObject, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:537
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:571
 in pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:571
 in #call#71(::Array{Any,1}, ::PyCall.PyObject, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:574
 in (::PyCall.PyObject)(::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:574
 in include_from_node1(::String) at .\loading.jl:488
while loading C:\Users\JohnRinehart\Downloads\test\test.jl, in expression starting on line 12
```

**Comment by malmaud** [comment]
What is `typeof(df)`?

**Comment by fuzzybear3965** [comment]
In the broken case it's a `Dict{Any,Any}` and `PyCall.PyObject` in the working case.

**Comment by malmaud** [comment]
Hmm, I guess the conversion is still happening. But at any rate, as we discussed in https://github.com/JuliaPy/PyCall.jl/issues/376, we're just going to change PyCall to not try to convert DataFrames to Julia dictionaries, which will solve this.

**Comment by fuzzybear3965** [comment]
Okay, that sounds good. Thanks for working on this, @malmaud. I look forward to checking out the master branch of PyCall.

**Comment by malmaud** [comment]
I'm going to close this in favor of https://github.com/JuliaPy/PyCall.jl/pull/384.

**Comment by stevengj** [comment]
@malmaud, when developing a Julia wrapper package around a Python package via PyCall, I generally would recommend avoiding automatic conversions in many places anyway, by using `foo["..."]` instead of `foo[:....]` and `pycall(foo, PyObject, ...)` instead of `foo(...)`.  This not only gives you greater control over conversion and is more reliable, but it is also faster because it skips the type-introspection test (and allows you to opt-in to copy-free containers like `PyVector`, `PyArray`, and `PyDict`).

**Comment by malmaud** [comment]
The issue is that usually the automatic conversion is what's wanted, though - if you call a method on a wrapped Pandas dataframe that happens to return a bool or a string etc, it should be converted to a Julia type. But if the method happens to return another dataframe, then I don't want it converted to a Julia dict.

**Comment by malmaud** [comment]
Maybe the best approach for the wrapper then is to 
* always get back a PyObject, 
* check if it's an instance of a Python type the wrapper is wrapping,
* and if not, try PyCall's automatic conversion

**Comment by stevengj** [comment]
Most Python functions return a predictable type.  e.g. the constructor for the type you are wrapping (e.g. a dataframe) should always return that type — you would never need to convert to any other Julia type, and even a sanity check seems somewhat unnecessary (an error would presumably occur later anyway).

And if you are expecting it to return some other type, say a bool or a list, you can convert the PyObject directly to this type with e.g. `Bool(::PyObject)` or `pycall(foo, Bool, ...args...)`.  (It will throw an error if the object is not convertable to that type.)  No need for the automatic conversion.

**Comment by stevengj** [comment]
Sorry, I didn't read your earlier message.  Yes, in the case where a function returns either a dataframe or an arbitrary type, you would either just use the auto-conversion (given JuliaPy/PyCall.jl#384) or check for a dataframe first and then try the auto-conversion afterwards as you suggest.

**Comment by malmaud** [comment]
For sure the constructors should avoid automatic conversion.
But each dataframe has hundreds of methods, some of which return dataframes and some which return bools etc, and I didn't want to manually annotate the expected return type of each.
But yes, it sounds like we're on the same page now.
